domain: "0.0.0.0:32001"
swaggeApiHost: "127.0.0.1:32001"
swaggeApi: true
autoMigrate: false
baseUrl:
  nianYin: "https://m.nianyin.com"
  shuYin: "https://www.shuyinfm.com"
  ting: "https://www.ting2.com"
